### ISSUE TITLE
Question on AllowReordering

### ISSUE THREAD

**Issue by lovesharyn** [felipecsl/AsymmetricGridView#24]
Hi,
I'm trying to use the library with allow reordering but i'm not able to enable the reordering of the grid.
The demo app doesn't support reordering as well.
Is the allow reordering feature broken in the library for now?
Looking forward to hear from you soon.
Cheers.

**Comment by felipecsl** [comment]
Hi, the reordering functionality is working as expected, as far as I know. Check the code on latest master for the current implementation. The sample app in the Play store is outdated, I'll update it with the latest code onde version 2.0.0 is out
