### ISSUE TITLE
AsymmetricGridViewAdapter Constructor is different

### ISSUE THREAD

**Issue by KingWu** [felipecsl/AsymmetricGridView#28]
compile 'com.felipecsl.asymmetricgridview:library:1.1.0'

I found this Constructor
public AsymmetricGridViewAdapter(android.content.Context context, com.felipecsl.asymmetricgridview.library.widget.AsymmetricGridView listView, java.util.List<T> items) 

But, in sample project, i found that,
private AsymmetricGridViewAdapter<?> getNewAdapter() {
        return new AsymmetricGridViewAdapter<DemoItem>(this, listView, adapter);
}

Doesn't match. Don't know how to use the library

**Comment by jesielin** [comment]
my solution is clone this library and import module native

**Comment by felipecsl** [comment]
The current version on master is still unreleased and has some major internal changes to `AsymmetricGridViewAdapter`. I'll send out a new version to maven central this week with the latest code

**Comment by supersume** [comment]
Still waiting. My project heavily depends on this.

**Comment by felipecsl** [comment]
I haven't had time to test this thoroughly, but if you've been using it already without problems, I'll go ahead and push to maven central

**Comment by felipecsl** [comment]
Ok just pushed version 2.0.0 to Maven Central. It should be live in a couple hours.
