### ISSUE TITLE
Cannot use AsymmetricGridView with an adapter that contains multiple view types

### ISSUE THREAD

**Issue by supersume** [felipecsl/AsymmetricGridView#30]
When using an adapter with multiple view types (in my case 4), the overridden method getViewTypeCount() never gets called. The adapter only uses one view type in getView (the first one to be inflated). Please provide a fix for this. Thanks.

**Comment by RoRoche** [comment]
Did you try to override the AsymmetricGridViewAdapter class? So that you can provide your expected values such as:

    @Override
    public int getViewTypeCount() {
        return wrappedAdapter.getViewTypeCount();
    }

    @Override
    public int getItemViewType(int position) {
        return wrappedAdapter.getItemViewType(position);
    }

**Comment by supersume** [comment]
Yes I have done that. The result is that multiple view types now appear,
but their assignment is random. They don't follow any rules that I set in
my adapter class.

**Comment by supersume** [comment]
I have found a temporary workaround. In the getview() method of my adapter, I don't write the code 

if (convertView != null)

The result is that the getview() method will always instantiate a new view hence view recycling is non existent. My guess is, the problem is with views that have been cached by the adapter. The method viewPool.get() in AsymmetricGridViewAdapter.java seems to be returning the wrong view type from cache.
