### ISSUE TITLE
Remove ic_launcher icon from library as it clashes with the client when using Gradle plugin 1.2.3

### ISSUE THREAD

**Issue by jjvargas** [felipecsl/AsymmetricGridView#31]
I get duplicated error when using 'com.android.tools.build:gradle:1.2.3'

**Comment by felipecsl** [comment]
good point. can you send a quick PR?

**Comment by felipecsl** [comment]
Fixed

**Comment by ChrisMpitzios** [comment]
i just tried to use it and the error is still there..

**Comment by felipecsl** [comment]
I didn't push a new release with this change yet. Expect one later today

**Comment by ChrisMpitzios** [comment]
thanks

**Comment by felipecsl** [comment]
Version 2.0.1 pushed to maven central. Expect it to be available in ~10 minutes
