### ISSUE TITLE
Green background of row

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [felipecsl/AsymmetricGridView#41]
I have set setRequestedColumnCount(3);..If there is one image in the row it shows a green background of the row.I have not set green background anywhere.Why is that and how can i remove it?

**Comment by shabbirsphinx** [comment]
I am facing same issue. @bkjbkjbnkj687698698 you got any solution for this ? Would love to hear from you. Any help appreciated.

**Comment by bkjbkjbnkj687698698** [comment]
@shabbirsphinx  Yeah u have to download library update it and add as module to ur project.Just change the colour in library where they have set default green background..

**Comment by felipecsl** [comment]
it could be because you have `setDebugging` to true, which causes the background to be set to custom colors
