### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by Yonony** [felipecsl/AsymmetricGridView#48]
Increasing the content of this gridview a memory overflow, increased memory and will not be released, the question whether there is notice?

**Comment by Yonony** [comment]
Out of memory

Increasing the content of this gridview a memory overflow, increased memory and will not be released, the question whether there is notice?

**Comment by felipecsl** [comment]
Please provide a more descriptive issue and a sample project to help reproduce, if possible. There is not much that can be done based on this description.
