### ISSUE TITLE
you should modify the README.md

### ISSUE THREAD

**Issue by tttony3** [felipecsl/AsymmetricGridView#53]
hi
i use {compile 'com.felipecsl.asymmetricgridview:library:2.0.1'} ,and i find it is different than library.

**Comment by tttony3** [comment]
the old version was always been OOM when contains a lot of imageview

**Comment by felipecsl** [comment]
What is wrong about the readme?
Also your second comment doesn't seem related to the issue at all (and doesn't provide any constructive feedback on steps to reproduce, for example)

**Comment by tttony3** [comment]
no ,i just wanna you release a new version 2.0.2  :)

**Comment by felipecsl** [comment]
Im working on version 3.0.0 which will add support for RecyclerView. I don't plan to update 2.x anymore
