### ISSUE TITLE
Using inside Scrollview

### ISSUE THREAD

**Issue by nishantt12** [felipecsl/AsymmetricGridView#54]
I want to use it inside scrollview. 

I have a photo grid inside scrollview. So, can i use it inside Scrollview with only Scrollview should scroll, "AsymmetricGridView" should not get scrolled.

or can you guys suggest any better way of doing this.

**Comment by felipecsl** [comment]
using a ListView instead of a ScrollView is a really bad idea. I think you should reconsider your layout ;)
