### ISSUE TITLE
Implement library

### ISSUE THREAD

**Issue by Gabik7** [felipecsl/AsymmetricGridView#60]
Hello i have some problem with implementation of AssymetricGridView it still crashing but i dont know what is wrong how to implement it correctly with my adapter there is error Link to AssymetricGridView library. Thank you

Adapter must be an instance of AsymmetricGridViewAdapter
                                                                      at com.felipecsl.asymmetricgridview.library.widget.AsymmetricGridView.setAdapter(AsymmetricGridView.java:71)
                                                                      at com.gabriel.movies.fragment.MainFragment.render(MainFragment.java:140)
                                                                      at com.gabriel.movies.fragment.MainFragment$MyTask.onPostExecute(MainFragment.java:228)
                                                                      at com.gabriel.movies.fragment.MainFragment$MyTask.onPostExecute(MainFragment.java:161)
My code

<com.felipecsl.asymmetricgridview.library.widget.AsymmetricGridView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/gridView1"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

AsymmetricGridView gridview;
List<ItemCategory> list;
AdapterCategory adapter;

    gridview = (AsymmetricGridView) mRootView.findViewById(R.id.gridView1);
    gridview.setRequestedColumnWidth(Utils.dpToPx(getActivity(), 120));

    list = new ArrayList<ItemCategory>();

    adapter = new AdapterCategory(getActivity(), R.layout.fragment_worcipe_main_item, list);
    gridview.setAdapter(adapter);
and adapter code

public class AdapterCategory extends ArrayAdapter<ItemCategory> {
    ItemCategory object;
    private Activity activity;
    private List<ItemCategory> item;
    private int row;

     public AdapterCategory(Activity act, int resource, List<ItemCategory> arrayList) {
            super(act, resource, arrayList);
            this.activity = act;
            this.row = resource;
            this.item = arrayList;
        }

        @Override
        public View getView(final int position, View convertView, ViewGroup parent) {
            View view = convertView;
            ViewHolder holder;

            if (view == null) {
                LayoutInflater inflater = (LayoutInflater) activity.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
                view = inflater.inflate(row, null);
                holder = new ViewHolder();
                view.setTag(holder);
            } else {
                holder = (ViewHolder) view.getTag();
            }

            if ((item == null) || ((position + 1) > item.size()))
                return view;

            object = item.get(position);

            holder.title = (TextView) view.findViewById(R.id.category_title);
            holder.image = (ImageView) view.findViewById(R.id.category_image);

            holder.title.setText(object.getCategoryName());

            Picasso.with(getContext()).load(RecipeConfig.SERVER_URL + "/upload/" +
                    object.getCategoryImageurl()).placeholder(R.drawable.ic_thumbnail).into(holder.image);

            return view;
        }

        public class ViewHolder {
            public TextView title;
            public ImageView image;

        }
    }

**Comment by Steve2955** [comment]
I'm also still trying to get the gridview working but, as far as i can see you have to extend your AdapterCategory from AsymmetricGridViewAdapter<ItemCategory>

my GridAdapter looks like this at the moment:

```
public class GridAdapter extends AsymmetricGridViewAdapter<GridItem> {
    Context context;
    public GridAdapter(Context context, AsymmetricGridView listView, List<GridItem> items) {
        super(context, listView, items);
        this.context=context;
    }

    public View getActualView(int position, View convertView, ViewGroup parent) {
        TextView v;
        GridItem item = (GridItem) getItem(position);
        if (convertView == null) {
            v = new TextView(context);
            v.setGravity(17);
            v.setTextColor(Color.parseColor("#ffffff"));
            v.setTextSize((float) Utils.dpToPx(context, 18.0f));
            v.setId(item.getPosition());
        } else {
            v = (TextView) convertView;
        }
        v.setText(item.getText());
        return v;
    }
}
```

But this is also not working because in this line of code `super(context, listView, items);` items is a wrong argument. If you have any cloe on how to get this working please let me know

**Comment by felipecsl** [comment]
Your `AdapterCategory` needs to extend `AsymmetricGridViewAdapter`
